services:
  easy-gate:
    build: .
    container_name: easy-gate
    networks:
      - easy-gate-net
    ports:
      - 8080:8080
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./easy-gate.json:/etc/easy-gate/easy-gate.json

networks:
  easy-gate-net:
    driver: bridge
