services:
  easy-gate:
    build: .
    container_name: easy-gate
    network_mode: host
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./easy-gate.json:/etc/easy-gate/easy-gate.json
